### PR TITLE
rfc for TWGC admin sdk repo transform

### PR DESCRIPTION
**Pull request by SamYuan1990**
Hi team,

Hope by this RFC, we can one step further for decouple peer cli works.

Signed-off-by: Sam Yuan <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@denyeart , @bestbeforetoday , @davidkhala , @xiaohui249 , @channingduan , @Peng-Du, @jkneubuh
FYI.

**Comment by bestbeforetoday** [comment]
I fully support this initiative to develop a programmatic API that can replace the varying admin capabilities in legacy SDKs, and provide a programmatic alternative to existing CLI commands. This would provide a good foundation on which to base CLI commands that are decoupled from the core Fabric implementation - in other words to replace the peer CLI commands - although actually delivering those CLI commands doesn't necessarily need to be within the scope of this RFC. There is a lot of value in providing an admin API that can be used by a Kubernetes operator; particularly a Golang API.

I think it is important that dependencies are kept relatively minimal, and certainly must **not** include core Fabric. For Fabric protobuf bindings, the ones documented [here](https://hyperledger.github.io/fabric-protos/) should be fine to use, and are probably better than generating new bindings.

Just for reference, there is at least a partial CLI implementation in the [fabric-cli](https://github.com/hyperledger/fabric-cli) repository which it might be possible to rebase on this new admin API rather than the legacy fabric-sdk-go.

**Review by jt-nti — APPROVED** [review]
I definitely support this RFC- the described admin SDK would provide a really solid foundation for a new Fabric CLI, CI/CD tools e.g. GitHub actions, etc.

**Review by bestbeforetoday — APPROVED** [review]

**Review by mbwhite — APPROVED** [review]
Excellent start; a dedicated admin library is long overdue for Fabric. 

I'm looking at it for being able to support the Ansible Scripts (https://ibm-blockchain.github.io/ansible-collection/modules.html) not all the required function is there yet, but this will give a great starting point.

**Review by denyeart — APPROVED** [review]

**Review by andrew-coleman — APPROVED** [review]

**Comment by denyeart** [comment]
I've sent a mailing list notification that this RFC is in Final Comment Period. We intend to merge the RFC and open a github repository within a week.

**Comment by denyeart** [comment]
No unresolved comments... I'll go ahead and merge and open the fabric respository.

**Pull request merged**
