### PR TITLE
RFC for ledger checkpointing

### PR DESCRIPTION
**Pull request by manish-sethi**
Signed-off-by: manish <manish.sethi@gmail.com>

### CODE REVIEW

**Comment by denyeart** [comment]
I had reviewed a draft of the RFC, so I am good with current version.

**Review by roger505 — COMMENTED** [review]
Is it possible makes sure that it is possible to create the check the checkpoint at the  current ledger height, and not wait for a triggering block. Our client does not work 24*7 so would want to take the checkpoint when no new blocks are being cut.

**Comment by manish-sethi** [comment]
> Is it possible makes sure that it is possible to create the check the checkpoint at the current ledger height, and not wait for a triggering block. Our client does not work 24*7 so would want to take the checkpoint when no new blocks are being cut.

Yes, sure. We can take the height `0` in the checkpoint request as a special case, which would be interpreted as the current height. However, the term current height will be a bit loosely defined here.

**Review by denyeart — APPROVED** [review]

**Comment by denyeart** [comment]
Not many comments on this RFC, probably because the draft was well reviewed even before the RFC got opened.
Let's enter Final Comment Period to give people one final week to review.

**Review by mastersingh24 — APPROVED** [review]

**Pull request merged**
